# Generated by Django 4.1.4 on 2022-12-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('deleted_at', models.DateField()),
                ('title', models.CharField(max_length=150)),
                ('file_upload', models.FileField(upload_to=None)),
                ('file_path', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'uploadfile',
                'permissions': (('read-upload-file', 'can read file'), ('delete-upload-file', 'can  delete file'), ('edit-upload-file', 'can edit file'), ('create-upload-file', 'can create file')),
            },
        ),
    ]
