# Generated by Django 4.1.4 on 2022-12-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('file_upload', models.FileField(upload_to=None)),
                ('file_path', models.CharField(max_length=150)),
            ],
        ),
    ]
